name: Build

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: yarn --frozen-lockfile --check-files

      - name: Build
        run: yarn build
