name: Lint

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  code:
    name: Lint code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.7.12
        with:
          install-command: yarn --frozen-lockfile --check-files --silent

      - name: Lint
        run: yarn lint
