name: Lint

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  code:
    name: Lint code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v4.1.1

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.7.7
        with:
          install-command: yarn --frozen-lockfile --check-files --silent

      - name: Lint
        run: yarn lint

      - name: Commit formatted files
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: "chore: Fix formatting"
